name: AkashaOS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write   # needed to push gh-pages
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      - name: Run tests
        run: pytest -q || true

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build docs
        run: mkdocs build --clean

      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Package repo
        run: |
          mkdir -p dist
          zip -r dist/AkashaOS-${{ github.sha }}.zip . -x ".git/*"

      - uses: actions/upload-artifact@v3
        with:
          name: AkashaOS-${{ github.sha }}
          path: dist/AkashaOS-${{ github.sha }}.zip
